nav:
  - Home: index.md
  - Python: python_study.md
  - STL: STL.md
  - Cmake: cmake.md
  - Conda: conda.md
  - Docker: docker.md
  - Git: git.md
  - Vim: vim.md
  - alias: alias.md
  - Ubuntu: ubuntu_apt.md
  - Linux: linux_command.md
  - SSH: ssh.md
  - 图床: photo_bed.md
  - 零碎知识: knowledge.md
  - 链接收藏: link.md
  - 论文收藏: pdfs.md
  - 博客收藏: blog.md
  - 友链: friend.md

site_name: 竹星 · 梦华 # 网站名字
site_url: http://www.wxzhu.top/ # 网站地址
site_author: zwx # 作者名

theme:
  name: material # 主题
  logo: img/zxmh.png
  favicon: img/zxmh.png
  custom_dir: overrides
  palette:
    - scheme: default # 日间模式
      primary: custom
      accent: custom # 链接等可交互元件的高亮色
  language: zh # 一些提示性的文字会变成中文
# edit_uri: edit/main/docs # 编辑按钮跳转的链接 
# repo_url: https://wenxin-zhu.github.io # 右上角点击跳转的链接
# repo_name: wenxin-zhu.github.io # 右上角的名字
  icon: 
    repo: fontawesome/brands/github #右上角图标
  features: 
    - header.autohide  # 自动隐藏标题 
    # - announce.dismiss # 当用户单击该按钮时，当前公告将被关闭，并且不会再次显示，直到公告内容发生更改
    # 导航
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    # - navigation.path # 导航路径
    # - navigation.tabs # 顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    - toc.follow # 当启用目录的锚点跟随时，侧边栏会自动滚动，以便活动锚点始终可见
    # - navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    # - navigation.expand # 打开Tab时左侧目录全部展开
    #- navigation.indexes # 启用章节索引页后，文档可以直接附加到章节，这对于提供概述页面特别有用
    # - navigation.footer # 页脚可以包含指向当前页面的上一页和下一页的链接
    # - navigation.top # 返回顶部的按钮 在上滑时出现
    # 进度指示器
    - navigation.instant
    - navigation.instant.progress
    # 搜索
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.share #搜索分享按钮
    - content.code.copy # 代码复制

copyright: Copyright &copy; 2023 ZWX # 左下角的版权声明

plugins:
  - search
  - git-revision-date-localized: # 用于将上次更新日期添加到您的网站页面
      locale: zh

extra_javascript:
  - javascripts/extra.js

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences